"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bhy+dk156xm+x=r+wk@crp!30ou^83jp_tizz1py#=ru$y4q_3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ip local, e ip de red local, (cmd, ipconfig,valor: Dirección IPv4)
ALLOWED_HOSTS = ["127.0.0.1","192.168.0.2","192.168.110.51"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #librerias
    'widget_tweaks',
    'storages',
    #mis aplicaciones
    'core.inventario',
    'core.login',
    'core.user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
]

ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # pongo la ruta de la carpeta de los templates
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# configuracion de la base de datos en desarrollo
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-419'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# configuracion de la carpeta de archivos estaticos
STATICFILES_DIRS = [
  os.path.join(BASE_DIR,"static")
  ]

# ruta a donde se manda el usuario despues de iniciar sesion
LOGIN_REDIRECT_URL = '/dashboard/'

# ruta a donde se manda el usuario despues de cerrar sesion
LOGOUT_REDIRECT_URL='login'

# ruta del inicio de sesion
LOGIN_URL='login'

#Carpeta raiz donde se guardaran nuestros archivos media, y se crea solo si estamos en desarrollo
if "WEBSITE_HOSTNAME" not in os.environ:
    MEDIA_ROOT=os.path.join(BASE_DIR, 'media/')

#Url absoluta para trabajar con los archivos media
MEDIA_URL='media/'

# modelo del usuario que mmodificamos
AUTH_USER_MODEL='user.User'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# confirgurar servidor para enviar correos
# host del envio de correos
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587

# configuracion de las credenciales de gmail para el envio emails
# obtengo las credenciales de azure o del local si estamos en desarrollo o desplegado
if 'WEBSITE_HOSTNAME' in os.environ: 
    config_email=os.environ['EMAIL_SEND']
    config_email_valores={i.split('=')[0]:i.split('=')[1] for i in config_email.split(' ')}
else:
    config_email_valores={
        'email':os.environ.get('CORREO'),
        'password':os.environ.get('PASS_CORREO')
    }
# correo de gmail que va a enviar correos
EMAIL_HOST_USER = config_email_valores['email']
# la contraseña
EMAIL_HOST_PASSWORD = config_email_valores['password']
EMAIL_USE_TLS = True